[[override]] 
  version = "0.1.0" 
  name = "gopkg.in/fatih/set.v0"
  
[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gochain-io/gochain"
  version = "2.1.42"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]] 
    name = "github.com/gochain-io/gochain" 
    unused-packages = false

